package szp.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * This is the AssignmentModel class that represents an assignment in the system.
 * It is annotated with @Data, a Lombok annotation to create all the getters, setters, equals, hash, and toString methods, based on the fields.
 * It is also annotated with @Entity, indicating that it is a JPA entity.
 * @Table(name = "assignment") is used to provide the details of the table that this entity will be mapped to.
 */
@Data
@Entity
@Table(name = "assignment")
public class AssignmentModel {

    /**
     * This is the id of the assignment.
     * It is generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "assignment_id")
    private Integer assignmentId;

    /**
     * This is the employee associated with the assignment.
     * It is a many-to-one relationship.
     */
    @ManyToOne
    @JoinColumn(name = "employee_id", nullable = false)
    private EmployeeModel employee;

    /**
     * This is the client associated with the assignment.
     * It is a many-to-one relationship.
     */
    @ManyToOne
    @JoinColumn(name = "client_id", nullable = false)
    private ClientModel client;

    /**
     * This is the description of the assignment.
     */
    @Column(name = "description", nullable = false)
    private String description;

    /**
     * This is the date of the assignment.
     */
    @Column(name = "assign_date", nullable = false)
    private  java.sql.Date  assignDate;

    /**
     * This is the cost of the assignment.
     */
    @Column(name = "cost", nullable = false)
    private Integer cost;

    /**
     * This is the state of the assignment.
     * It is an enumerated type.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "state", nullable = false)
    private State state;

    /**
     * This is the workstation associated with the assignment.
     * It is a one-to-one relationship.
     */
    @OneToOne
    @JoinColumn(name = "workstation_id")
    private WorkstationModel workstation;
}