package szp.model;

import jakarta.persistence.*;
import lombok.Data;

import java.util.List;

/**
 * This is the ClientModel class that represents a client in the system.
 * It is annotated with @Data, a Lombok annotation to create all the getters, setters, equals, hash, and toString methods, based on the fields.
 * It is also annotated with @Entity, indicating that it is a JPA entity.
 * @Table(name = "client") is used to provide the details of the table that this entity will be mapped to.
 */
@Data
@Entity
@Table(name = "client")
public class ClientModel {

    /**
     * This is the id of the client.
     * It is generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "client_id")
    private Integer clientId;

    /**
     * This is the first name of the client.
     */
    @Column(name = "first_name", nullable = false)
    private String firstName;

    /**
     * This is the second name of the client.
     */
    @Column(name = "second_name")
    private String secondName;

    /**
     * This is the last name of the client.
     */
    @Column(name = "last_name", nullable = false)
    private String lastName;

    /**
     * This is the email of the client.
     */
    @Column(name = "email", nullable = false)
    private String email;

    /**
     * This is the phone number of the client.
     */
    @Column(name = "phone_number", nullable = false)
    private String phoneNumber;

    /**
     * This is the bank account of the client.
     */
    @Column(name = "bank_account", nullable = false)
    private String bankAccount;

    /**
     * This is the list of assignments associated with the client.
     * It is a one-to-many relationship.
     */
    @OneToMany(mappedBy = "client", cascade = CascadeType.ALL)
    private List<AssignmentModel> assignments;

}